name: Commit Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_commit:
    name: Check Commit
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - run: mise run check
        env:
          MISE_TASK_OUTPUT: "keep-order"
