name: Commit Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_commit:
    name: Check Commit
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      - run: mise run check
        env:
          MISE_TASK_OUTPUT: "keep-order"
