name: Commit Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_commit:
    name: Check Commit
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      - run: mise run check
        env:
          MISE_TASK_OUTPUT: "keep-order"
