name: update

on:
  push:
    branches:
      - "renovate/**"
  repository_dispatch:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SKIP_LIST: ${{ secrets.SKIP_LIST }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: yarn update
