name: Update

on:
  pull_request:
    branches:
      - main
  repository_dispatch:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SKIP_LIST: ${{ secrets.SKIP_LIST }}

jobs:
  update:
    name: Update
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: npx playwright install --with-deps chromium
      - run: yarn update
