name: update

on:
  push:
    branches:
      - "renovate/**"
  repository_dispatch:
  schedule:
    - cron: "30 0,3,9,15 * * *"
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SKIP_LIST: ${{ secrets.SKIP_LIST }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: yarn update
