name: update

on:
  pull_request:
    branches:
      - main
  repository_dispatch:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SKIP_LIST: ${{ secrets.SKIP_LIST }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: yarn update
