name: Update

on:
  pull_request:
    branches:
      - main
  repository_dispatch:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

env:
  HEADLESS: ${{ vars.HEADLESS }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SKIP_LIST: ${{ vars.SKIP_LIST }}

jobs:
  update:
    name: Update
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: npx playwright install --with-deps chromium
      - run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: user_data
          key: ${{ runner.os }}-${{ env.CURRENT_DATE }}
      - run: yarn update
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ !cancelled() }}
        with:
          path: screenshot
          if-no-files-found: ignore
